name: Test Pipeline

on: 
    push

jobs:
    check-env:
        runs-on: ubuntu-latest
        steps:
        - name: Print
          run: echo "Hello World"

        - name: checkout
          uses: actions/checkout@v4

        - name: List Files
          run: ls -al