name: Test Pipeline

on: 
    push

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Build artifact
          run: echo "Build finished" > build.txt

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Display files
          run: ls -al

        - name: Run tests
          run: echo "Tests"

    deploy:
        runs-on: ubuntu-latest
        needs: [ build, test ]

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: List files
          run: ls -al

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/actions:latest .
        
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: Push Image to DockerHub
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/actions:latest 
        