name: Test Pipeline

on: 
    push

jobs:
    check-env:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: install cowsay
          run: |
            sudo apt update
            sudo apt install cowsay
        
        - name: execute cowsay
          run: cowsay "Hello, world!" > cowsay.txt
        
        - name: print cowsay.txt
          run: cat cowsay.txt
        


        