name: push workflow

on: 
    push

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Load Dependencies
          uses: actions/cache@v4
          with:
            path: index.html
            key: ${{ runner.os }}-cache-index-${{ hashFiles('index.html') }}
        
        - name: Build artifact
          run: echo "Build finished" > build.txt

    test:
        runs-on: ubuntu-latest
        needs: build
        services:
          postgres:
            image: postgres
            env:
              POSTGRES_USER: user
              POSTGRES_PASSWORD: password
              POSTGRES_DB: db
            ports:
            - 5432:5432

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Display files
          run: ls -al

        - name: Run tests
          run: echo "Tests"
          env:
            POSTGRES_URL: postgres://user:password@localhost:5432/db

        - name: start k8s
          uses: azure/setup-kubectl@v4
          with:
            version: 'v1.30.0'
        
        - uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}
          
        - name: k8s get namespaces
          run: kubectl get ns

    deploy: 
        runs-on: ubuntu-latest
        needs: [ build, test ]

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: List files
          run: ls -al

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build Prod Docker Image
          if: github.ref_name == 'main'
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/actions:latest .
        
        - name: Build Dev Docker Image
          if: github.ref_name == 'dev'
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/actions-dev:latest .
          
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: Push Image to Prod DockerHub
          if: github.ref_name == 'main'
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/actions:latest 

        - name: Push Image to Dev DockerHub
          if: github.ref_name == 'dev'
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/actions-dev:latest 
        